const COURSE_ACTIONS = {
	SET_COURSES: 'SET_COURSES',
	UPDATE_COURSE: 'UPDATE_COURSE',
	ADD_COURSE: 'ADD_COURSE',
	SET_LOADING: 'SET_LOADING',
	SET_ERROR: 'SET_ERROR',
};

export default COURSE_ACTIONS;
