const PRODUCT_ACTIONS = {
	SET_PRODUCTS: 'SET_PRODUCTS',
	UPDATE_PRODUCT: 'UPDATE_PRODUCT',
	ADD_PRODUCT: 'ADD_PRODUCT',
	SET_LOADING: 'SET_LOADING',
	SET_ERROR: 'SET_ERROR',
	ADD_PRODUCTS: 'ADD_PRODUCTS',
};

export default PRODUCT_ACTIONS;
