const PRODUCT_ACTIONS = {
	SET_PRODUCTS: 'SET_PRODUCTS',
	UPDATE_PRODUCT: 'UPDATE_COURSE',
	ADD_COURSE: 'ADD_COURSE',
	SET_LOADING: 'SET_LOADING',
	SET_ERROR: 'SET_ERROR',
};

export default PRODUCT_ACTIONS;
